/* CPU-only driver replacement. Every CUDA operation fails before hardware. */
#define FAIL(name) int name(void) { return 999; }
FAIL(cuCtxCreate_v4)
FAIL(cuCtxDestroy_v2)
FAIL(cuCtxGetCurrent)
FAIL(cuCtxGetDevice)
FAIL(cuCtxPopCurrent_v2)
FAIL(cuCtxPushCurrent_v2)
FAIL(cuCtxSetCurrent)
FAIL(cuCtxSynchronize)
FAIL(cuDeviceGet)
FAIL(cuDeviceGetAttribute)
FAIL(cuDeviceGetCount)
FAIL(cuDevicePrimaryCtxRelease_v2)
FAIL(cuDevicePrimaryCtxRetain)
FAIL(cuEventCreate)
FAIL(cuEventDestroy_v2)
FAIL(cuEventQuery)
FAIL(cuEventRecord)
FAIL(cuFuncGetAttribute)
FAIL(cuGetErrorName)
FAIL(cuGetErrorString)
int cuInit(unsigned flags) { (void)flags; return 0; }
FAIL(cuIpcGetMemHandle)
FAIL(cuIpcOpenMemHandle_v2)
FAIL(cuLaunchKernel)
FAIL(cuMemAlloc_v2)
FAIL(cuMemcpyDtoDAsync_v2)
FAIL(cuMemcpyDtoD_v2)
FAIL(cuMemcpyDtoHAsync_v2)
FAIL(cuMemcpyDtoH_v2)
FAIL(cuMemcpyHtoDAsync_v2)
FAIL(cuMemcpyHtoD_v2)
FAIL(cuMemFree_v2)
FAIL(cuMemHostGetDevicePointer_v2)
FAIL(cuMemHostRegister_v2)
FAIL(cuMemHostUnregister)
FAIL(cuMemsetD8_v2)
FAIL(cuModuleGetFunction)
FAIL(cuModuleGetGlobal_v2)
FAIL(cuModuleLoadDataEx)
FAIL(cuModuleUnload)
FAIL(cuPointerGetAttribute)
FAIL(cuStreamCreate)
FAIL(cuStreamDestroy_v2)
FAIL(cuStreamSynchronize)

int cuKernelGetFunction(void **out, void *kernel) { if (out) *out = kernel; return 0; }
